### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by sytzemeijer** [foliagecanine/tritium-os#5]
it is giving a 'out of memory' error in qemu

**Comment by foliagecanine** [comment]
Could you give more details (full error message / screenshot, what hardware you are using)? Did you use `make run` to start the emulator?

**Comment by sytzemeijer** [comment]
Yes, I am using make run to build it

**Comment by foliagecanine** [comment]
I'm sorry, I need more details in order to diagnose the issue. Seeing as this hasn't gotten a comment in a while I'm going to go ahead and close it. Feel free to re-open the issue.
