### ISSUE TITLE
opposite ```mov``` opcodes resulting the wrong data segment in user mode

### ISSUE THREAD

**Issue by colorglass** [foliagecanine/tritium-os#6]
https://github.com/foliagecanine/tritium-os/blob/dc119fa911a86741bcbc5a18b036083dee64fdeb/kernel/arch/i386/sys/idt-asm.asm#L321-L327
The follow ```mov``` seem to make the opposite opcodes as the purpose here is to load the user data selector ```0x23``` into the data segment registers.

**Comment by foliagecanine** [comment]
You're right, thanks for letting me know. I pushed a fix.

**Comment by colorglass** [comment]
Also pay attention to the IRQ handler where a data segment reload is also needed.
